# use goreleaser for builds and containers
#
# TODO: @memes
#  - search for APP and update as needed
#  - modify labels, as needed
# spell-checker: disable
---
version: 2
project_name: APP
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}-{{ .Commit }}
    goos:
      - freebsd
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    # TODO: @memes - modify to match location of main package if not in root
    main: ./cmd/APP/
    mod_timestamp: '{{ .CommitTimestamp }}'
gomod:
  proxy: true
archives:
  - formats:
      - binary
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
source:
  enabled: true
  name_template: '{{ .ProjectName }}.src'
checksum:
  name_template: 'checksums.txt'
sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source
signs:
  - artifacts: checksum
    cmd: cosign
    signature: '${artifact}.sigstore.json'
    args:
      - sign-blob
      - '--bundle=${signature}'
      - '${artifact}'
      - '--yes'
    output: true
snapshot:
  version_template: '{{ incpatch .Tag }}-next'
changelog:
  disable: true
dockers_v2:
  - images:
      - 'memes/{{ .ProjectName }}'
      - 'ghcr.io/memes/{{ .ProjectName }}'
    tags:
      - latest
      - '{{ .Tag }}'
      - '{{ .Major }}'
    dockerfile: Dockerfile
    labels:
      maintainer: 'Matthew Emes <memes@matthewemes.com>'
      org.opencontainers.image.title: '{{ .ProjectName }}'
      org.opencontainers.image.authors: 'memes@matthewemes.com'
      org.opencontainers.image.description: '{{ .ProjectName }} description'
      org.opencontainers.image.licenses: 'MIT'
      org.opencontainers.image.created: '{{ .Date }}'
      org.opencontainers.image.source: '{{ .GitURL }}/tree/{{ .FullCommit }}'
      org.opencontainers.image.documentation: '{{ .GitURL }}/tree/{{ .FullCommit }}/README.md'
      org.opencontainers.image.version: '{{ .Version }}'
      org.opencontainers.image.revision: '{{ .FullCommit }}'
      org.opencontainers.image.url: '{{ .GitURL }}'
    annotations:
      - 'index:org.opencontainers.image.description': '{{ .ProjectName }} description'
docker_signs:
  - cmd: cosign
    output: true
    args:
      - sign
      - '${artifact}'
      - '--yes'
release:
  draft: false
  prerelease: auto
milestones:
  - close: true
    fail_on_error: false
    name_template: '{{ .Tag }}'
