# These github actions will perform linting using pre-commit.
# yamllint disable rule:line-length
# spell-checker: disable
---
name: pre-commit

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches-ignore:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      TALISMAN_VERSION: 1.37.0
    steps:
      - uses: actions/checkout@v5
      - name: Install talisman
        run: |
          sudo curl -fsSLo /usr/local/bin/talisman https://github.com/thoughtworks/talisman/releases/download/v${{ env.TALISMAN_VERSION }}/talisman_linux_amd64
          sudo chmod 0755 /usr/local/bin/talisman
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: pre-commit/action@v3.0.1
  # TODO: @memes - remove if not using a Dockerfile
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.2.0
        with:
          dockerfile: Dockerfile
